server:
  port: 8082

spring:
  application:
    name: employee-service

  data:
    mongodb:
      uri: mongodb+srv://mv172001:parkavenue47@mycluster.kc8k9e5.mongodb.net/employeeDb?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


